version: "3"

services:
  dwm-api:
    build: .
    container_name: dwm-api
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    command: bash -c "yarn && yarn knex:migrate && yarn start"
    ports:
      - "${API_PORT}:3333"
    networks:
      - dwm-network

networks:
  dwm-network:
    driver: bridge
